[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://jqyirecdnrtvnyjrjghf.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxeWlyZWNkbnJ0dm55anJqZ2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA2NDgyNDMsImV4cCI6MjA5NjIyNDI0M30.LFQJOzs9gWqfbOHFNYHYDiHh-RS5NFOY3dMG3A6i-DY"
